
#Sobrevivência empresarial em Pernambuco com base no PIB e nos dados abertos da RFB: uma análise em dois períodos sociopolítico econômicos da história do Brasil

##Elisângela P.M. Santana¹, Edivaldo R.S. Júnior², Cleide Lins de Almeida³
##SCRIPT 02 - AGREGAR

In [ ]:
#IMPORTACAO DAS BIBLIOTECAS 
import os
import numpy as np
import pandas as pd
os.getcwd()

'd:\\#PROJETOS\\FURG\\ECD-CIENCIA DE DADOS\\#TCC-FURG\\BASE-RFB-12-03-2022\\SCRIPTS'

In [ ]:
# IMPORTACAO DA TABELA EMPRESA
#cnpj_basico, #capital_social, #porte_empresa #Natureza Juridica

os.chdir('D:\#PROJETOS\FURG\ECD-CIENCIA DE DADOS\#TCC-FURG\BASE-RFB-12-03-2022\TRATADA')
empresaTratada = pd.read_csv('empresaTratada.csv', sep=',', encoding='UTF-8', usecols = ['CNPJ BASICO','NATJU','CAP_SOCIAL','PORTE'])
empresaTratada.head()

   CNPJ BASICO  NATJU CAP_SOCIAL  PORTE
0     41273603   2062   10000,00    1.0
1     41273604   2062   10000,00    1.0
2     41273605   2135    1000,00    1.0
3     41273606   2135   72000,00    1.0
4     41273607   2135       1,00    1.0

In [ ]:
#RENOMEAR COLUNA CNPJ BASICO
empresaTratada = empresaTratada.rename(columns={'CNPJ BASICO': 'CNPJ_BASICO'})

In [ ]:
empresaTratada.shape

(49151491, 4)

In [ ]:
#VERIFICAR VALORES FALTANTES
print(pd.isnull(empresaTratada).sum())

CNPJ_BASICO        0
NATJU              0
CAP_SOCIAL         0
PORTE          63173
dtype: int64

In [ ]:
#TAMANHO DA TABELA EMPRESA
empresaTratada.shape[0]

49151491

In [ ]:
empresaTratada.dtypes

CNPJ_BASICO      int64
NATJU            int64
CAP_SOCIAL      object
PORTE          float64
dtype: object

In [ ]:
# TRANSFORMAR COLUNA CAPITAL SOCIAL EM INTEIRO
# PASSO 01 - MUDAR VIRGULA PARA PONTO NA COLUNA CAP_SOCIAL
def mudarNumero(item):
  if ',' in item:
    return item.replace(',','.')
  else:
    return item

empresaTratada['CAP_SOCIAL'] = empresaTratada['CAP_SOCIAL'].apply(mudarNumero)
empresaTratada['CAP_SOCIAL'].head()

0    10000.00
1    10000.00
2     1000.00
3    72000.00
4        1.00
Name: CAP_SOCIAL, dtype: object

In [ ]:
#PASSO 02 TRANSFORMAR CAP_SOCIAL EM NUMERICO (float64)
empresaTratada['CAP_SOCIAL'] = pd.to_numeric(empresaTratada['CAP_SOCIAL'])
empresaTratada.dtypes

CNPJ_BASICO      int64
NATJU            int64
CAP_SOCIAL     float64
PORTE          float64
dtype: object

In [ ]:
print('Quantidade de registros',empresaTratada.shape[0])
print('Tipo de Registros','\n',empresaTratada.dtypes)

Quantidade de registros 49151491
Tipo de Registros
 CNPJ_BASICO      int64
NATJU            int64
CAP_SOCIAL     float64
PORTE          float64
dtype: object

In [ ]:
#EXPORTAR empresaTratada FORMATADA
empresaTratada.to_csv(r'empresaFormatada.csv', index = False)

In [ ]:
del empresaTratada

In [ ]:
# IMPORTACAO DA TABELA ESTABELECIMENTO
#cnpj_basico, ordem , dv  #Matriz ou Filial #sit_cadastral, #dt_sit_cadastral, #Mot_situação cadastral #dt_ini_atividade, #cnae_fisc_princ, #UF #municipio
os.chdir('D:\#PROJETOS\FURG\ECD-CIENCIA DE DADOS\#TCC-FURG\BASE-RFB-12-03-2022\TRATADA')
estabTratada = pd.read_csv('estabTratada.csv', sep=',', encoding='UTF-8', usecols= ['CNPJ_BASICO','CNPJ_ORDEM','CNPJ_DV','IDE_MAT_FIL','SIT_CADASTRAL','DATA_SIT_CADAS','MOT_SIT_CADAS','DATA_INI_ATV','CNAE_FISCAL','UF','MUNICIPIO'])

In [ ]:
#TAMANHO DA TABELA ESTABELECIMENTO
estabTratada.shape[0]

51860331

In [ ]:
#QUANTIDADE DE MATRIZ E FILIAL
estabTratada['IDE_MAT_FIL'].value_counts()

1    49151491
2     2708840
Name: IDE_MAT_FIL, dtype: int64

In [ ]:
#VERIFICAR VALORES FALTANTES
print(pd.isnull(estabTratada).sum())

CNPJ_BASICO       0
CNPJ_ORDEM        0
CNPJ_DV           0
IDE_MAT_FIL       0
SIT_CADASTRAL     0
DATA_SIT_CADAS    0
MOT_SIT_CADAS     0
DATA_INI_ATV      0
CNAE_FISCAL       0
UF                0
MUNICIPIO         0
dtype: int64

In [ ]:
# VERIFICANDO ESTRUTURA DA TABELA ESTABELECIMENTO
estabTratada.head()

,CNPJ_BASICO,CNPJ_ORDEM,CNPJ_DV,IDE_MAT_FIL,SIT_CADASTRAL,DATA_SIT_CADAS,MOT_SIT_CADAS,DATA_INI_ATV,CNAE_FISCAL,UF,MUNICIPIO
0,40521734,1,30,1,8,19911001,1,19910725,4744001,BA,3993
1,22257653,1,93,1,8,19881124,1,19860828,1412601,MG,4733
2,57680274,1,96,1,8,20081231,71,19870605,3211601,SP,6369
3,315164,1,8,1,8,20081231,71,19941122,3101200,MA,921
4,36174589,1,91,1,8,20150209,73,19900607,8888888,RJ,6001

In [ ]:
#VERIFICANDO TYPO DA TABELA ESTABELECIMENTO
estabTratada.dtypes

CNPJ_BASICO        int64
CNPJ_ORDEM         int64
CNPJ_DV            int64
IDE_MAT_FIL        int64
SIT_CADASTRAL      int64
DATA_SIT_CADAS     int64
MOT_SIT_CADAS      int64
DATA_INI_ATV       int64
CNAE_FISCAL        int64
UF                object
MUNICIPIO          int64
dtype: object

In [ ]:
#IMPORTAR TABELA CNAE
cnae =  pd.read_csv('D:\#PROJETOS\FURG\ECD-CIENCIA DE DADOS\#TCC-FURG\BASE-RFB-12-03-2022\TRATADA\cnae.csv', sep=',', encoding='UTF-8')

In [ ]:
#TIPO DA TABELA CNAE
cnae.dtypes

N_CNAE        int64
DESC_CNAE    object
dtype: object

In [ ]:
# IMPORTAR empresaTratada FORMATADA
empresaFormatada =  pd.read_csv('D:\#PROJETOS\FURG\ECD-CIENCIA DE DADOS\#TCC-FURG\BASE-RFB-12-03-2022\TRATADA\empresaFormatada.csv', sep=',', encoding='UTF-8')

In [ ]:
empresaFormatada.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49151491 entries, 0 to 49151490
Data columns (total 4 columns):
 #   Column       Dtype
---  ------       -----
 0   CNPJ_BASICO  int64
 1   NATJU        int64
 2   CAP_SOCIAL   float64
 3   PORTE        float64
dtypes: float64(2), int64(2)
memory usage: 1.5 GB

In [ ]:
estabTratada.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51860331 entries, 0 to 51860330
Data columns (total 11 columns):
 #   Column          Dtype
---  ------          -----
 0   CNPJ_BASICO     int64
 1   CNPJ_ORDEM      int64
 2   CNPJ_DV         int64
 3   IDE_MAT_FIL     int64
 4   SIT_CADASTRAL   int64
 5   DATA_SIT_CADAS  int64
 6   MOT_SIT_CADAS   int64
 7   DATA_INI_ATV    int64
 8   CNAE_FISCAL     int64
 9   UF              object
 10  MUNICIPIO       int64
dtypes: int64(10), object(1)
memory usage: 4.3+ GB

In [ ]:
#JUNTAR DATASET EMPRESA E ESTABELECIMENTO
empresaFormatada.info()
estabTratada.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49151491 entries, 0 to 49151490
Data columns (total 4 columns):
 #   Column       Dtype
---  ------       -----
 0   CNPJ_BASICO  int64
 1   NATJU        int64
 2   CAP_SOCIAL   float64
 3   PORTE        float64
dtypes: float64(2), int64(2)
memory usage: 1.5 GB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51860331 entries, 0 to 51860330
Data columns (total 11 columns):
 #   Column          Dtype
---  ------          -----
 0   CNPJ_BASICO     int64
 1   CNPJ_ORDEM      int64
 2   CNPJ_DV         int64
 3   IDE_MAT_FIL     int64
 4   SIT_CADASTRAL   int64
 5   DATA_SIT_CADAS  int64
 6   MOT_SIT_CADAS   int64
 7   DATA_INI_ATV    int64
 8   CNAE_FISCAL     int64
 9   UF              object
 10  MUNICIPIO       int64
dtypes: int64(10), object(1)
memory usage: 4.3+ GB

In [ ]:
#JUNTAR DATASET EMPRESA E ESTABELECIMENTO
empresasBrasil = pd.merge(empresaFormatada, estabTratada, how = 'outer', on = 'CNPJ_BASICO')

In [ ]:
#VERIFICAR VALORES FALTANTES
print(pd.isnull(empresasBrasil).sum())

#EXPORTAR TABELA EMPRESAS BRASIL (Empresa + Estabelecimento)
os.chdir('D:\#PROJETOS\FURG\ECD-CIENCIA DE DADOS\#TCC-FURG\BASE-RFB-12-03-2022\TRATADA')
empresasBrasil.to_csv(r'empresasBrasil.csv', index = False)

CNPJ_BASICO           0
NATJU              7831
CAP_SOCIAL         7831
PORTE             71018
CNPJ_ORDEM           10
CNPJ_DV              10
IDE_MAT_FIL          10
SIT_CADASTRAL        10
DATA_SIT_CADAS       10
MOT_SIT_CADAS        10
DATA_INI_ATV         10
CNAE_FISCAL          10
UF                   10
MUNICIPIO            10
dtype: int64

In [ ]:
print('Registros Base Estabelecimentos', estabTratada.shape)
print('Registros Base Empresas Brasil', empresasBrasil.shape)
print('Diferença de registros', empresasBrasil.shape[0] - estabTratada.shape[0])

#QUANTIDADE DE MATRIZ E FILIAL
print('Quantidade de Matriz e Filiais','\n',empresasBrasil['IDE_MAT_FIL'].value_counts(),'\n')

Registros Base Estabelecimentos (51860331, 11)
Registros Base Empresas Brasil (51860355, 14)
Diferença de registros 24
Quantidade de Matriz e Filiais
 1.0    49151493
2.0     2708852
Name: IDE_MAT_FIL, dtype: int64

In [ ]:
#VERIFICAR VALORES FALTANTES
print(pd.isnull(empresasBrasil).sum())

CNPJ_BASICO           0
NATJU              7831
CAP_SOCIAL         7831
PORTE             71018
CNPJ_ORDEM           10
CNPJ_DV              10
IDE_MAT_FIL          10
SIT_CADASTRAL        10
DATA_SIT_CADAS       10
MOT_SIT_CADAS        10
DATA_INI_ATV         10
CNAE_FISCAL          10
UF                   10
MUNICIPIO            10
dtype: int64

In [ ]:
#IMPORTAR TABELA SIMPLES PARA IDENTIFICAÇÃO DO MEI
os.chdir('D:\#PROJETOS\FURG\ECD-CIENCIA DE DADOS\#TCC-FURG\BASE-RFB-12-03-2022\TRATADA')
simples = pd.read_csv('simples.csv', sep=',', encoding='UTF-8', usecols=['CNPJ BASICO', 'OPÇÃO PELO SIMPLES','MEI'])

In [ ]:
simples.tail()

          CNPJ BASICO OPÇÃO PELO SIMPLES MEI
31095258     98763352                  N   N
31095259     98764285                  S   N
31095260     98764665                  S   N
31095261     98819295                  S   N
31095262     98819568                  N   N

In [ ]:
simples = simples.rename(columns={'CNPJ BASICO': 'CNPJ_BASICO','OPÇÃO PELO SIMPLES': 'OP_SIMPLES'})

In [ ]:
simples.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31095263 entries, 0 to 31095262
Data columns (total 3 columns):
 #   Column       Dtype
---  ------       -----
 0   CNPJ_BASICO  int64
 1   OP_SIMPLES   object
 2   MEI          object
dtypes: int64(1), object(2)
memory usage: 711.7+ MB

In [ ]:
#JUNTAR DATASERT EMPRESA (Empresa + Estabelecimento + Simples)
empresasBrasil = pd.merge(empresasBrasil, simples, how = 'outer', on = 'CNPJ_BASICO')

In [ ]:
#EXPORTAR TABELA EMPRESAS BRASIL (Empresa + Estabelecimento + Simples)
os.chdir('D:\#PROJETOS\FURG\ECD-CIENCIA DE DADOS\#TCC-FURG\BASE-RFB-12-03-2022\TRATADA')
empresasBrasil.to_csv(r'empresasBrasil02.csv', index = False)

In [ ]:
empresasBrasil.shape

(51860364, 16)

In [ ]:
empresasBrasil.head()

,CNPJ_BASICO,NATJU,CAP_SOCIAL,PORTE,CNPJ_ORDEM,CNPJ_DV,IDE_MAT_FIL,SIT_CADASTRAL,DATA_SIT_CADAS,MOT_SIT_CADAS,DATA_INI_ATV,CNAE_FISCAL,UF,MUNICIPIO,OP_SIMPLES,MEI
0,41273603,2062.0,10000.0,1.0,1.0,44.0,1.0,2.0,20210318.0,0.0,20210318.0,4789099.0,PR,7535.0,S,N
1,41273604,2062.0,10000.0,1.0,1.0,99.0,1.0,2.0,20210318.0,0.0,20210318.0,8592901.0,RS,8625.0,S,N
2,41273605,2135.0,1000.0,1.0,1.0,33.0,1.0,2.0,20210318.0,0.0,20210318.0,5620104.0,SP,7107.0,S,S
3,41273606,2135.0,72000.0,1.0,1.0,88.0,1.0,2.0,20210318.0,0.0,20210318.0,4712100.0,GO,9625.0,S,S
4,41273607,2135.0,1.0,1.0,1.0,22.0,1.0,2.0,20210318.0,0.0,20210318.0,7319002.0,GO,9361.0,S,S

In [ ]:
empresasBrasil.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 51860364 entries, 0 to 51860363
Data columns (total 16 columns):
 #   Column          Dtype
---  ------          -----
 0   CNPJ_BASICO     int64
 1   NATJU           float64
 2   CAP_SOCIAL      float64
 3   PORTE           float64
 4   CNPJ_ORDEM      float64
 5   CNPJ_DV         float64
 6   IDE_MAT_FIL     float64
 7   SIT_CADASTRAL   float64
 8   DATA_SIT_CADAS  float64
 9   MOT_SIT_CADAS   float64
 10  DATA_INI_ATV    float64
 11  CNAE_FISCAL     float64
 12  UF              object
 13  MUNICIPIO       float64
 14  OP_SIMPLES      object
 15  MEI             object
dtypes: float64(12), int64(1), object(3)
memory usage: 6.6+ GB

In [ ]:
empresasBrasil.describe()

,CNPJ_BASICO,NATJU,CAP_SOCIAL,PORTE,CNPJ_ORDEM,CNPJ_DV,IDE_MAT_FIL,SIT_CADASTRAL,DATA_SIT_CADAS,MOT_SIT_CADAS,DATA_INI_ATV,CNAE_FISCAL,MUNICIPIO
count,5.186036e+07,5.185252e+07,5.185252e+07,5.178934e+07,5.186034e+07,5.186034e+07,5.186034e+07,5.186034e+07,5.186034e+07,5.186034e+07,5.186034e+07,5.186034e+07,5.186034e+07
mean,2.722666e+07,2.317312e+03,5.253402e+07,2.223827e+00,7.711886e+00,4.500027e+01,1.052234e+00,4.915002e+00,2.008394e+07,1.856553e+01,2.008188e+07,5.874496e+06,5.797467e+03
std,1.970050e+07,5.797695e+02,2.125923e+09,1.810654e+00,1.668484e+02,3.043785e+01,2.224977e-01,2.791020e+00,1.109824e+06,2.924082e+01,1.280232e+05,2.357171e+06,2.582352e+03
min,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,4.100813e+06,1.113010e+05,1.000000e+00
25%,1.212754e+07,2.135000e+03,0.000000e+00,1.000000e+00,1.000000e+00,1.700000e+01,1.000000e+00,2.000000e+00,2.010041e+07,0.000000e+00,2.000122e+07,4.712100e+06,4.123000e+03
50%,2.481671e+07,2.135000e+03,1.000000e+03,1.000000e+00,1.000000e+00,4.400000e+01,1.000000e+00,4.000000e+00,2.018020e+07,1.000000e+00,2.013022e+07,4.923001e+06,6.387000e+03
75%,3.760886e+07,2.135000e+03,1.000000e+04,5.000000e+00,1.000000e+00,7.100000e+01,1.000000e+00,8.000000e+00,2.020102e+07,6.300000e+01,2.018092e+07,8.219999e+06,7.535000e+03
max,9.901778e+07,8.885000e+03,1.000000e+12,5.000000e+00,9.999000e+03,9.900000e+01,2.000000e+00,8.000000e+00,2.022031e+07,8.000000e+01,2.022031e+07,9.900800e+06,9.997000e+03

In [ ]:
#VERIFICAR VALORES FALTANTES
print(pd.isnull(empresasBrasil).sum())

CNPJ_BASICO              0
NATJU                 7840
CAP_SOCIAL            7840
PORTE                71027
CNPJ_ORDEM              19
CNPJ_DV                 19
IDE_MAT_FIL             19
SIT_CADASTRAL           19
DATA_SIT_CADAS          19
MOT_SIT_CADAS           19
DATA_INI_ATV            19
CNAE_FISCAL             19
UF                      19
MUNICIPIO               19
OP_SIMPLES        19900293
MEI               19900293
dtype: int64

In [ ]:
empresasBrasil.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 51860364 entries, 0 to 51860363
Data columns (total 16 columns):
 #   Column          Dtype
---  ------          -----
 0   CNPJ_BASICO     int64
 1   NATJU           float64
 2   CAP_SOCIAL      float64
 3   PORTE           float64
 4   CNPJ_ORDEM      float64
 5   CNPJ_DV         float64
 6   IDE_MAT_FIL     float64
 7   SIT_CADASTRAL   float64
 8   DATA_SIT_CADAS  float64
 9   MOT_SIT_CADAS   float64
 10  DATA_INI_ATV    float64
 11  CNAE_FISCAL     float64
 12  UF              object
 13  MUNICIPIO       float64
 14  OP_SIMPLES      object
 15  MEI             object
dtypes: float64(12), int64(1), object(3)
memory usage: 6.6+ GB